name: 배포 알리미

on:
  workflow_call:
    inputs:
      team:
        description: "팀명 (ex. Front-End, Back-End, Core)"
        type: string
        required: true
        default: 테스트 팀
      service-name:
        description: "서비스명 (ex. 스매치, 스매치어드민, 패스트매치)"
        type: string
        required: true
        default: 테스트 서비스
      environment:
        description: "배포 환경 (test, stage, prod)"
        type: string
        required: true
        default: 테스트 환경

    secrets:
      SLACK_DISTRIBUTION_NOTIFICATION_WEBHOOK_URL:
        description: "Slack 웹훅 주소"
        required: true

jobs:
  distribution-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack-notify
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "team": "${{ inputs.team }}",
              "serviceName": "${{ inputs.service-name }}",
              "environment": "${{ inputs.environment }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DISTRIBUTION_NOTIFICATION_WEBHOOK_URL }}
