name: AWS ECR 로그인 및 도커 이미지 빌드 및 푸시

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      ecr-repository:
        description: 빌드 후 이미지를 푸시 할 ECR 레지스트리 이름
        required: true
        type: string
      docker-build-args:
        description: 이미지 빌드 시 --build-args 로 전달할 인자
        required: false
        type: string
      image-tag:
        description: 이미지 푸시할 때 사용할 이미지 태그
        required: true
        type: string
      alias-tag:
        description: 이미지 푸시할 때 보조로 사용할 이미지 태그
        required: false
        type: string

    secrets:
      AWS_ACCESS_KEY_ID:
        description: 'AWS 액세스 키 ID'
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS 시크릿 액세스 키'
        required: true

jobs:
  build-and-push:
    if: "${{ !(endsWith(github.ref, '/main') && startsWith(github.event.head_commit.message, 'chore: release v')) }}"

    runs-on: ubuntu-latest-8-cores

    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - id: ecr
        uses: aws-actions/amazon-ecr-login@v1

      - uses: docker/setup-buildx-action@v2

      - run: |      
          ecr_registry_and_repository=${{ steps.ecr.outputs.registry }}/${{ inputs.ecr-repository }}

          if [ -z "${{ inputs.alias-tag }}" ]
          then
            echo "DOCKER_TAGS=$ecr_registry_and_repository:${{ inputs.image-tag }}" >> $GITHUB_ENV
          else
            echo "DOCKER_TAGS=$ecr_registry_and_repository:${{ inputs.image-tag }},$ecr_registry_and_repository:${{ inputs.alias-tag }}" >> $GITHUB_ENV
          fi

      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.DOCKER_TAGS }}
          build-args: ${{ inputs.docker-build-args }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - if: github.event_name == 'pull_request'
        uses: peter-evans/find-comment@v2
        id: comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 도커 이미지가 빌드되었습니다.

      - if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            도커 이미지가 빌드되었습니다. (`${{ env.DOCKER_TAGS }}`)
          edit-mode: replace

      - if: github.event_name == 'pull_request'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: preview