name: EKS 저장소 이미지 태그 업데이트

on:
  workflow_call:
    inputs:
      image-tag:
        description: 이미지 푸시할 때 사용할 태그
        required: true
        type: string
      chart-path:
        description: 헬름 차트 위치
        required: true
        type: string
      values-file:
        description: 이미지 태그를 반영할 파일 이름 (values.yaml)
        required: true
        type: string
      environment:
        description: 환경 구분 (e.g. prod, stage, dev)
        required: true
        type: string 

    secrets:
      PERSONAL_TOKEN:
        required: true

jobs:
  update-eks-image-tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 
        with:
          repository: smatch-corp/eks
          token: ${{ secrets.PERSONAL_TOKEN }}

      - id: get-email
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const { data } = await github.rest.users.getByUsername({
              username: context.actor,
            });

            return data.email;

      - env:
          ACTOR_NAME: ${{ github.actor }}
          ACTOR_EMAIL: ${{ steps.get-email.outputs.result }}
          IMAGE_TAG: ${{ inputs.image-tag }}
          VALUE_FILE: ${{ inputs.values-file }}
          ENVIRONMENT: ${{ inputs.environment }}
        working-directory: ${{ inputs.chart-path }}
        run: |
          git config user.name "$ACTOR_NAME"
          git config user.email "$ACTOR_EMAIL"

          sed -i  -E 's/tag: .*/tag: '"$IMAGE_TAG"'/g' "$VALUE_FILE"
          git add .
          git commit -m "ci(${{ inputs.chart-path }}/$ENVIRONMENT): update image tag to $IMAGE_TAG"
          git pull --rebase origin main && git push origin main